#!/bin/bash
MIEYAOU_HOME="$HOME"/.config/mieyaou
bin_ext=/result/bin/nvim

get_nix_cmd() {
  if [ -f "$MIEYAOU_HOME"/nix-portable ]; then
    echo "$MIEYAOU_HOME"/nix-portable
  else
    echo nix
  fi
}

nixcmd=$(get_nix_cmd)

maybe_install_nix() {
  if $nixcmd --version >/dev/null 2>&1; then
    read -r -n 1 -p "Nix is not availabe on the system, would you like to proceed with installation? (y/n)" yn
    case $yn in
      [Yy]* ) echo -e "\nProceeding with installation, preferring portable on supported systems.";;
      [Nn]* ) echo -e "\nSetup cancelled, aborting." && exit
    esac
    platform=$(uname)
    if [ "$platform" = "Darwin" ]; then
      # match with git repo convention
      sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install)
    else
      echo "Nix installation not found, downloading portable version."
      curl -L https://github.com/DavHau/nix-portable/releases/latest/download/nix-portable-"$(uname -m)" >./nix-portable
      chmod +x ./nix-portable || (echo "Failed to install nix-portable. Exiting." && exit)
      echo "Nix portable installed successfully."
      nixcmd=$(pwd)/nix-portable
    fi
  else
    echo "Nix already installed or available in system."
  fi
}

update_miaou() {
  cwd=$(pwd)
  cd "$MIEYAOU_HOME" || (echo "Config dir not present, cannot update" && exit)
  nix flake update miaou || (echo "Failed to update miaou. Terminating." && exit)
  rm -rf ./result
  nix build . --refresh || (echo "Failed to update miaou. Terminating." && exit)

  cd "$cwd" || (echo "Could not return to working directory." && exit)
  echo "Successfully updated miaou."
}

# actual script

if [[ "$1" = "-h" || "$1" = "--help" || ! -f "$MIEYAOU_HOME$bin_ext" ]]; then
  echo -e "usage: mieyaou <your file> OR --<flag>\nflags:\n\t--update: fetch updates to the miaou definitions\n\t--rebuild: rebuild from locally stored meows\n\t--setup: perform first-time setup operations"
elif [ "$1" = "--update" ]; then
  update_miaou
elif [ "$1" = "--setup" ]; then
  cwd=$(pwd)
  if ! ls "$MIEYAOU_HOME" >/dev/null 2>&1; then
    echo "Config dir not initialized, creating directory."
    mv "$(dirname "$(realpath "$0")")" "$MIEYAOU_HOME"
    cd "$MIEYAOU_HOME" || (echo "Failed to create config dir." && exit)
  else
    if [ "$MIEYAOU_HOME" != "$(pwd)" ]; then
      cd "$MIEYAOU_HOME" || (echo "Config dir already exists, but we could not change to it." && exit)
    fi
  fi
  maybe_install_nix
  cd "$cwd" || (echo "Could not return to previous directory." && exit)
  echo "First-time setup completed, now building."
  update_miaou
  echo "Mieyaou updated."
else
  "$MIEYAOU_HOME$bin_ext" "$@"
fi
